### ISSUE TITLE
ConcurrentModificationException on schema, investigate!!!!!

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#10]
`
2015-03-11 12:43:15,606 ERROR [VirtualGroupLoadGuru.recalculateVirtualGroupAsync-27733-thread-1] VirtualGroupLoadGuru:552 - Failed internalWalkDownAndAddOrRemoveVirtualGroups. 
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
        at java.util.HashMap.putMapEntries(HashMap.java:511)
        at java.util.HashMap.putAll(HashMap.java:784)
        at org.umlg.sqlg.structure.SchemaManager.getEdgeForeignKeys(SchemaManager.java:1016)
        at org.umlg.sqlg.structure.SqlgVertex.internalGetVertices(SqlgVertex.java:504)
        at org.umlg.sqlg.structure.SqlgVertex.vertices(SqlgVertex.java:344)
        at org.umlg.sqlg.strategy.SqlgVertexStep.flatMap(SqlgVertexStep.java:45)
        at org.apache.tinkerpop.gremlin.process.graph.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:48)
        at org.apache.tinkerpop.gremlin.process.traversal.step.AbstractStep.hasNext(AbstractStep.java:134)
        at org.apache.tinkerpop.gremlin.process.traversal.DefaultTraversal.hasNext(DefaultTraversal.java:115)
        at org.umlg.runtime.collection.persistent.BaseCollection.loadManyNotPrimitiveNotDataType(BaseCollection.java:1449)
        at org.umlg.runtime.collection.persistent.BaseCollection.loadFromVertex(BaseCollection.java:75)
        at org.umlg.runtime.collection.persistent.BaseCollection.maybeLoad(BaseCollection.java:811)
        at org.umlg.runtime.collection.persistent.BaseCollection.add(BaseCollection.java:169)
        at org.umlg.runtime.collection.persistent.BaseCollection.addIgnoreInverse(BaseCollection.java:162)
        at com.rorotika.cm.network.AbstractWorkspaceElement.addToVirtualGroupIgnoreInverse(AbstractWorkspaceElement.java:347)
        at com.rorotika.cm.network.virtualgroup.VirtualGroupLoadGuru.lambda$internalWalkDownAndAddOrRemoveVirtualGroups$13(VirtualGroupLoadGuru.java:513)
        at com.rorotika.cm.network.virtualgroup.VirtualGroupLoadGuru$$Lambda$118/1746798919.visit(Unknown Source)
        at com.rorotika.cm.etl.meta.EtlElement.walkNetworkElementsForRealAndPlan(EtlElement.java:482)
        at com.rorotika.cm.network.virtualgroup.VirtualGroupLoadGuru.internalWalkDownAndAddOrRemoveVirtualGroups(VirtualGroupLoadGuru.java:505)
        at com.rorotika.cm.network.virtualgroup.VirtualGroupLoadGuru.walkDownAndAddVirtualGroup(VirtualGroupLoadGuru.java:438)
        at com.rorotika.cm.network.virtualgroup.VirtualGroupLoadGuru.recalculateVirtualGroup(VirtualGroupLoadGuru.java:195)
        at com.rorotika.cm.network.virtualgroup.VirtualGroupLoadGuru.lambda$recalculateVirtualGroupAsync$3(VirtualGroupLoadGuru.java:73)
        at com.rorotika.cm.network.virtualgroup.VirtualGroupLoadGuru$$Lambda$137/726698298.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by pietermartin** [comment]
Can not duplicate.
