### ISSUE TITLE
Error in postgres batch mode with empty string property

### ISSUE THREAD

**Issue by yura-ata** [pietermartin/sqlg#106]
Exception is thrown when vertex with single empty string attribute is created useing batch mode. Looks like empty string is treated as NULL. 

Simple example:

```
this.sqlgGraph.tx().normalBatchModeOn();
this.sqlgGraph.addVertex("A", Collections.singletonMap("emptyProperty", ""));
this.sqlgGraph.tx().commit();
Vertex a = this.sqlgGraph.traversal().V().hasLabel("A").next();
assertEquals("", a.property("emptyProperty").value());

```
and Exception:

java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: currval of sequence "V_A_ID_seq" is not yet defined in this session

	at org.umlg.sqlg.sql.dialect.PostgresDialect.flushVertexCache(PostgresDialect.java:254)
	at org.umlg.sqlg.structure.BatchManager.flush(BatchManager.java:189)
	at org.umlg.sqlg.structure.SqlgTransaction.doCommit(SqlgTransaction.java:73)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:105)
	at org.umlg.sqlg.test.batch.TestNormalBatchPrimitive.testEmptyString(TestNormalBatchPrimitive.java:526)

**Comment by pietermartin** [comment]
As it happens this issue was raised and fixed 10 minutes before by @JPMoresmau 
https://github.com/pietermartin/sqlg/issues/103
