### ISSUE TITLE
Query with condition on a previous edge seems not working

### ISSUE THREAD

**Issue by imhy** [pietermartin/sqlg#116]
Hi, All!
Seems this queries not working on a Sqlg.
https://gist.github.com/imhy/67140ed7e246cda0f5e8f8cf0ac196e8

Regards, Sergey.

**Comment by pietermartin** [comment]
This has been fixed on the `removeHazelcast` branch.
This branch will be merged into master soon.
Sqlg can not optimize the `RepeatStep` of your gremlin as its to complex. There was a bug where the incoming element to emit was not being fake labeled on non optimized `RepeatStep`s and thus not returned by the sql. Fake labels is Sqlg's way of knowing the element needs to be in the select clause.

**Comment by imhy** [comment]
Thank You!

**Comment by pietermartin** [comment]
@imhy I fixed the bug. Can you check that its working your side?

**Comment by imhy** [comment]
Hi! Seems now test working.
But when I try to use sqlg to create graph (creation process more complex than in test) in our development environment I get error:

ava.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: prepared statement "S_3" does not exist
	at org.umlg.sqlg.structure.SqlgVertex.internalAddVertex(SqlgVertex.java:348)
	at org.umlg.sqlg.structure.SqlgVertex.insertVertex(SqlgVertex.java:293)
	at org.umlg.sqlg.structure.SqlgVertex.<init>(SqlgVertex.java:39)
	at org.umlg.sqlg.structure.SqlgGraph.addVertex(SqlgGraph.java:357)
	at org.umlg.sqlg.structure.TopologyManager.addEdgeLabel(TopologyManager.java:128)
	at org.umlg.sqlg.structure.Schema.createEdgeLabel(Schema.java:184)
	at org.umlg.sqlg.structure.Schema.ensureEdgeLabelExist(Schema.java:150)
	at org.umlg.sqlg.structure.Topology.ensureEdgeLabelExist(Topology.java:524)
	at org.umlg.sqlg.structure.SqlgVertex.addEdgeInternal(SqlgVertex.java:149)
	at org.umlg.sqlg.structure.SqlgVertex.addEdge(SqlgVertex.java:117)

**Comment by pietermartin** [comment]
Are you on Postgresql 9.6?
I recently upgraded the jdbc driver to the latest and started getting "ERROR: cached plan must not change result type".
I had hoped #140 resolved that.

Your error seems a different thought.

If you can duplicate the error I'll look at it.
