### ISSUE TITLE
As and Select return nothing on topology traversals

### ISSUE THREAD

**Issue by JPMoresmau** [pietermartin/sqlg#132]
This works:

```
    	Vertex a1 = this.sqlgGraph.addVertex(T.label, "Person", "name", "a1");
        Vertex a2 = this.sqlgGraph.addVertex(T.label, "Person", "name", "a2");
        a1.addEdge("friend", a2, "weight", 5);
        this.sqlgGraph.tx().commit();

        try (GraphTraversal<Vertex, Vertex> gt = this.sqlgGraph.traversal()
                .V().hasLabel("Person").has("name","a1").as("v1")
                .values("name").as("name1")
                .select("v1")
                .out("friend");){
        	Assert.assertTrue(gt.hasNext());
        	Assert.assertEquals(a2, gt.next());
        	Assert.assertFalse(gt.hasNext());
        }
```

This doesn't:

```
       Vertex gis = this.sqlgGraph.addVertex(T.label, "Gis", "name", "HaloGis1");
        Vertex something = this.sqlgGraph.addVertex(T.label, "Something", "name", "Something1");
        gis.addEdge("testEdge", something, "edgeProperty", "asdasd");
        this.sqlgGraph.tx().commit();
        assertEquals(2, this.sqlgGraph.topology().V().hasLabel("sqlg_schema.schema").as("schema").select("schema").out("schema_vertex").count().next().intValue());
        assertEquals(2, this.sqlgGraph.topology().V().hasLabel("sqlg_schema.schema").as("schema").values("name").as("schemaName").select("schema").out("schema_vertex").count().next().intValue());
    
```

**Comment by pietermartin** [comment]
hmm, tricky one, those queries are not even being optimized. It will take some investigation to see whats going on.

**Comment by pietermartin** [comment]
Found the bug, the code ends up calling `SqlgVertex.edges(...)` and that has `sqlgGraph.traversal()` hardcoded. In this case it should be `sqlgGraph.topology()`

**Comment by JPMoresmau** [comment]
Yes, i've just found that as well, but fixing this fails later:

```
java.lang.NullPointerException
	at org.umlg.sqlg.sql.parse.SchemaTableTree.printFromClauseFor(SchemaTableTree.java:1263)
	at org.umlg.sqlg.sql.parse.SchemaTableTree.constructFromClause(SchemaTableTree.java:1187)
	at org.umlg.sqlg.sql.parse.SchemaTableTree.constructSinglePathSql(SchemaTableTree.java:664)
	at org.umlg.sqlg.sql.parse.SchemaTableTree.constructSinglePathSql(SchemaTableTree.java:640)
	at org.umlg.sqlg.sql.parse.SchemaTableTree.constructSql(SchemaTableTree.java:334)
	at org.umlg.sqlg.strategy.SqlgSqlExecutor.executeRegularQuery(SqlgSqlExecutor.java:33)
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.executeRegularQuery(SqlgCompiledResultIterator.java:237)
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.hasNextLazy(SqlgCompiledResultIterator.java:115)
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.hasNext(SqlgCompiledResultIterator.java:78)
	at org.umlg.sqlg.process.SqlgRawIteratorToEmitIterator.flattenRawIterator(SqlgRawIteratorToEmitIterator.java:61)
	at org.umlg.sqlg.process.SqlgRawIteratorToEmitIterator.hasNext(SqlgRawIteratorToEmitIterator.java:43)
	at org.umlg.sqlg.strategy.SqlgGraphStepCompiled.processNextStart(SqlgGraphStepCompiled.java:64)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:179)
	at org.umlg.sqlg.test.topology.TestTopology.testTopologyTraversal(TestTopology.java:35)
```

**Comment by JPMoresmau** [comment]
Obviously all the code around getting the possible tables for SchemaTableTree hides the schema table, which is not what we want in our case.

**Comment by pietermartin** [comment]
Reopening this to add in the topology edges to the topology cache.
This should mean we can remove the `propertyTypeMap` null check in `SchemaTableTree` and for the future when topology edges might have properties things will just work.
Kinda hard to test now as topology edges do not have any properties at present.

**Comment by JPMoresmau** [comment]
This unfortunately doesn't fix my underlying issue with my code. A traversal using out on topology items works fine, doesn't work as soon as I have as/select in it. So there is still another issue there.

**Comment by pietermartin** [comment]
But you `TestTopology.testTopologyTraversal` test for that no? Can you post a query that fails?

**Comment by JPMoresmau** [comment]
works:
```
assertEquals(2, this.sqlgGraph.topology().V().hasLabel("sqlg_schema.schema").has("name",P.within("MySchema")).as("schema").values("name").as("schemaName").select("schema").out("schema_vertex").count().next().intValue());
```
Fails
```
assertTrue(this.sqlgGraph.topology().V().hasLabel("sqlg_schema.schema").has("name",P.within("MySchema")).as("schema").values("name").as("schemaName").select("schema").out("schema_vertex").hasNext());   
```

**Comment by pietermartin** [comment]
Ok, not sure why its failing yet.
The first query gets optimized by TinkerPop to only count the edges.
So the `out("schema_vertex")` becomes `outE("schema_vertex")`
This is not happening with the second.

**Comment by JPMoresmau** [comment]
ok, great

**Comment by JPMoresmau** [comment]
I confirm, changing `vertices` locally fixes my issues.
