### ISSUE TITLE
build sqlg enviroment

### ISSUE THREAD

**Issue by gflp123** [pietermartin/sqlg#167]
Dear 
How to build sqlg enviroment. Thanks.

**Comment by pietermartin** [comment]
You build it with maven. 

`mvn clean install`
or
`mvn -DskipTests clean install`

**Comment by gflp123** [comment]
Dear
Using PostgreSQL database,How to solve it.Thanks
java.lang.RuntimeException: java.lang.IllegalStateException: Could not find suitable sqlg plugin for the JDBC URL: jdbc:postgresql://localhost:5432/sqlgraphdb
	at org.umlg.sqlg.structure.SqlgGraph.<init>(SqlgGraph.java:284)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:225)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:216)
	at org.umlg.sqlg.test.BaseTest.before(BaseTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Could not find suitable sqlg plugin for the JDBC URL: jdbc:postgresql://localhost:5432/sqlgraphdb
	at org.umlg.sqlg.structure.SqlgGraph.<init>(SqlgGraph.java:271)
	... 30 more

**Comment by pietermartin** [comment]
It looks like from the stack trace that you are running the test from eclipse.
Chances are that you are running the test from the wrong context?
The suitable plugin it is talking about is specified in `sqlg/sqlg-postgres-parent/sql-postgres-dialect/src/main/resources/META-INF/org.umlg.sqlg.SqlgPlugin`

The exception is saying that it could not find that file in the class path.

Perhaps give me more information on how you are trying to execute the test.
Is the project properly build in eclipse? i.e. all the maven modules are loaded and the resource directories marked as source?
