### ISSUE TITLE
Check exceptions thrown semantics when table/label does not exist

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#18]
```
qtp904396018-222 WARN  org.restlet.Component.EtlServerRestletApplication  - Exception or error caught in server resource
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: relation "public.V_CellNeighbourQuery" does not exist
  Position: 15
	at org.umlg.sqlg.structure.SqlgGraphStep._verticesUsingLabel(SqlgGraphStep.java:180)
	at org.umlg.sqlg.structure.SqlgGraphStep.getVerticesUsingLabel(SqlgGraphStep.java:113)
	at org.umlg.sqlg.structure.SqlgGraphStep.vertices(SqlgGraphStep.java:91)
	at org.umlg.sqlg.structure.SqlgGraphStep.lambda$new$25(SqlgGraphStep.java:39)
	at org.umlg.sqlg.structure.SqlgGraphStep$$Lambda$49/339881373.get(Unknown Source)
	at org.apache.tinkerpop.gremlin.process.traversal.step.sideEffect.GraphStep.processNextStart(GraphStep.java:94)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:116)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:32)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:127)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.forEachRemaining(Traversal.java:175)
	at org.umlg.runtime.adaptor.UmlgSqlgGraph.allInstances(UmlgSqlgGraph.java:158)
	at com.rorotika.cm.gis.CellNeighbourQuery.allInstances(CellNeighbourQuery.java:249)
	at com.rorotika.cm.admin.initialize.GisInitialize.buildHuaweiCellNeighbourQueries(GisInitialize.java:113)
	at com.rorotika.cm.admin.initialize.GisInitialize.captureGisNeighbourQuery(GisInitialize.java:38)
	at com.rorotika.cm.restlet.meta.NetworkSoftwareVersionAddedListenerResourceImpl.get(NetworkSoftwareVersionAddedListenerResourceImpl.java:59)
```

**Comment by pietermartin** [comment]
Can not duplicate.
