### ISSUE TITLE
TopologyUpgrade crashes special function indexes

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#194]
```
CREATE INDEX "V_EMSC_EOS_idx2"
  ON "HOUR"."V_EMSC_EOS"
  USING btree
  (date_trunc('hour'::text, "COLLECTTIME_hour"));
```
Some users created these indexes outside of Sqlg.
When recreating the `sqlg_schema` the following exception occurs.

```
Caused by: java.lang.IllegalStateException: Property date_trunc('hour'::text, "COLLECTTIME_hour") for AbstractLabel HOUR.EMSC_EOS does not exists
        at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
        at org.umlg.sqlg.structure.TopologyManager.addIndex(TopologyManager.java:343)
        at org.umlg.sqlg.structure.SqlgStartupManager.loadSqlgSchemaFromInformationSchema(SqlgStartupManager.java:196)
        at org.umlg.sqlg.structure.SqlgStartupManager.loadSchema(SqlgStartupManager.java:70)
        at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:228)
        at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:217)
        at com.rorotika.cm.admin.NetAggregateGraph.<init>(NetAggregateGraph.java:52)
        at com.rorotika.cm.admin.NetAggregateGraph.<clinit>(NetAggregateGraph.java:19)
```
Going to just not add the index if the property does not exist.

**Comment by pietermartin** [comment]
Fixed with https://github.com/pietermartin/sqlg/commit/30fab558da0d880f4312de1831dfe9e0a56417e2
