### ISSUE TITLE
Unable to use postgres for graph

### ISSUE THREAD

**Issue by rmanzar** [pietermartin/sqlg#299]
I am following step by step as detailed on http://www.sqlg.org/
but when i do :install org.umlg sqlg-postgres 1.5.1, it gives me this error
Error grabbing Grapes -- [unresolved dependency: org.umlg#sqlg-postgres;1.5.1: not found]

This is happening on Linux and also on my windows desktop,

I tried everything as described on https://github.com/pietermartin/sqlg/issues/201

I have already tried :uninstall  sqlg-postgres
Please let me know what is causing this issue.

**Comment by pietermartin** [comment]
I had a look. Sqlg is currently on TinkerPop 3.3.1 and the 3.3.1 binaries for the console are no longer on the download page.
So looking at upgrading to 3.3.3 and then testing the console again.

**Comment by rmanzar** [comment]
As suggested, I tried 3.3.3 with sqlg 1.5.1 and 1.5.2 both , neither worked.

got the same error with both
Error grabbing Grapes -- [unresolved dependency: org.umlg#sqlg-postgres;1.5.2: not found]
Error grabbing Grapes -- [unresolved dependency: org.umlg#sqlg-postgres;1.5.1: not found]

**Comment by pietermartin** [comment]
I have just managed to get Sqlg to work on 3.3.3.
I''ll try out the console later and let you know.

**Comment by pietermartin** [comment]
Ok got it to work on 3.3.3.
Sqlg 1.5.2-SNAPSHOT is deployed on the maven snapshot repo,

```
pieter@pieter-Precision-7510:~/Downloads/tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin$ chmod 775 gremlin.sh 
pieter@pieter-Precision-7510:~/Downloads/tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin$ ./gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :install org.umlg sqlg-postgres 1.5.2-SNAPSHOT
==>Loaded: [org.umlg, sqlg-postgres, 1.5.2-SNAPSHOT]
gremlin> :plugin list
==>tinkerpop.server[active]
==>tinkerpop.gephi
==>tinkerpop.utilities[active]
==>tinkerpop.sugar
==>tinkerpop.credentials
==>tinkerpop.tinkergraph[active]
==>sqlg.postgres
gremlin> :plugin use sqlg.postgres
==>sqlg.postgres activated
gremlin> graph = SqlgGraph.open('/home/pieter/Projects/sqlg/sqlg/sqlg-postgres-parent/sqlg-postgres/src/test/resources/sqlg.properties')
java.lang.IllegalStateException
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.lang.IllegalStateException
	at org.apache.tinkerpop.gremlin.structure.Graph.traversal(Graph.java:159)
	at org.umlg.sqlg.structure.SqlgGraph.traversal(SqlgGraph.java:341)
	at org.umlg.sqlg.structure.SqlgGraph.topology(SqlgGraph.java:345)
	at org.umlg.sqlg.structure.topology.TopologyManager.updateGraph(TopologyManager.java:50)
	at org.umlg.sqlg.structure.SqlgStartupManager.createOrUpdateGraph(SqlgStartupManager.java:178)
	at org.umlg.sqlg.structure.SqlgStartupManager.loadSqlgSchema(SqlgStartupManager.java:97)
 ... 
Caused by: java.lang.ClassNotFoundException: org.umlg.sqlg.structure.SqlgGraph
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies$GlobalCache.getStrategies(TraversalStrategies.java:260)
	... 59 more
gremlin> :exit
pieter@pieter-Precision-7510:~/Downloads/tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin$ ./gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: sqlg.postgres
plugin activated: tinkerpop.tinkergraph
gremlin> :plugin use sqlg.postgres
==>sqlg.postgres activated
gremlin> graph = SqlgGraph.open('/home/pieter/Projects/sqlg/sqlg/sqlg-postgres-parent/sqlg-postgres/src/test/resources/sqlg.properties')
==>sqlggraph[SqlGraph] (jdbc:postgresql://localhost:5432/sqlgraphdb)
gremlin> g = graph.traversal()
==>sqlggraphtraversalsource[sqlggraph[SqlGraph] (jdbc:postgresql://localhost:5432/sqlgraphdb), standard]
gremlin> g.V().count()
==>5
gremlin> 
```

**Comment by rmanzar** [comment]
I appreciate your help here. 

I still get the same error, tried on 2 linux boxes, both give the same error. 

I only have put the 3.3.3 console on the fresh linux install. 
Did you do anything prior to the steps listed above.

**Comment by pietermartin** [comment]
Here is the complete steps I followed. This time deleting all the cached stuff I know about.
```
pieter@pieter-Precision-7510:~/Downloads/tinkerpop$ rm -rf ~/.groovy
pieter@pieter-Precision-7510:~/Downloads/tinkerpop$ rm -rf ~/.m2/repository/org/umlg
pieter@pieter-Precision-7510:~/Downloads/tinkerpop$ unzip apache-tinkerpop-gremlin-console-3.3.3-bin.zip
...
  inflating: apache-tinkerpop-gremlin-console-3.3.3/lib/groovy-2.4.15.jar  
  inflating: apache-tinkerpop-gremlin-console-3.3.3/lib/groovy-sql-2.4.15-indy.jar  
  inflating: apache-tinkerpop-gremlin-console-3.3.3/lib/groovy-2.4.15-indy.jar  
pieter@pieter-Precision-7510:~/Downloads/tinkerpop$ cd apache-tinkerpop-gremlin-console-3.3.3/bin/
pieter@pieter-Precision-7510:~/Downloads/tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin$
pieter@pieter-Precision-7510:~/Downloads/tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin$ ./gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :install org.umlg sqlg-postgres 1.5.2-SNAPSHOT
==>Error grabbing Grapes -- [unresolved dependency: org.umlg#sqlg-postgres;1.5.2-SNAPSHOT: not found]
gremlin> :exit 
pieter@pieter-Precision-7510:~/Downloads/tinkerpop$ cd ..
pieter@pieter-Precision-7510:~/Downloads$ mkdir sqlg
pieter@pieter-Precision-7510:~/Downloads$ cd sqlg
pieter@pieter-Precision-7510:~/Downloads/sqlg$ git clone git@github.com:pietermartin/sqlg.git
Cloning into 'sqlg'...
remote: Counting objects: 35753, done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 35753 (delta 47), reused 161 (delta 27), pack-reused 35557
Receiving objects: 100% (35753/35753), 7.32 MiB | 420.00 KiB/s, done.
Resolving deltas: 100% (14659/14659), done.
pieter@pieter-Precision-7510:~/Downloads/sqlg$ cd sqlg/
pieter@pieter-Precision-7510:~/Downloads/sqlg/sqlg$ mvn clean install -DskipTests
...
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
[INFO] Replacing /home/pieter/Downloads/sqlg/sqlg/sqlg-benchmark-h2/target/benchmarks.jar with /home/pieter/Downloads/sqlg/sqlg/sqlg-benchmark-h2/target/sqlg-benchmark-h2-1.5.2-SNAPSHOT-shaded.jar
[INFO] 
[INFO] --- maven-install-plugin:2.5.1:install (default-install) @ sqlg-benchmark-h2 ---
[INFO] Installing /home/pieter/Downloads/sqlg/sqlg/sqlg-benchmark-h2/target/sqlg-benchmark-h2-1.5.2-SNAPSHOT.jar to /home/pieter/.m2/repository/org/umlg/sqlg-benchmark-h2/1.5.2-SNAPSHOT/sqlg-benchmark-h2-1.5.2-SNAPSHOT.jar
[INFO] Installing /home/pieter/Downloads/sqlg/sqlg/sqlg-benchmark-h2/pom.xml to /home/pieter/.m2/repository/org/umlg/sqlg-benchmark-h2/1.5.2-SNAPSHOT/sqlg-benchmark-h2-1.5.2-SNAPSHOT.pom
[INFO] Installing /home/pieter/Downloads/sqlg/sqlg/sqlg-benchmark-h2/target/sqlg-benchmark-h2-1.5.2-SNAPSHOT-sources.jar to /home/pieter/.m2/repository/org/umlg/sqlg-benchmark-h2/1.5.2-SNAPSHOT/sqlg-benchmark-h2-1.5.2-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] sqlg ............................................... SUCCESS [  1.013 s]
[INFO] sqlg :: core ....................................... SUCCESS [  6.088 s]
[INFO] sqlg :: test ....................................... SUCCESS [  7.292 s]
[INFO] sqlg :: sqlg ....................................... SUCCESS [  0.008 s]
[INFO] sqlg :: postgres dialect ........................... SUCCESS [  1.594 s]
[INFO] sqlg :: postgres ................................... SUCCESS [  0.809 s]
[INFO] sqlg :: sqlg-hsqldb-parent ......................... SUCCESS [  0.008 s]
[INFO] sqlg :: hsqldb dialect ............................. SUCCESS [  1.008 s]
[INFO] sqlg :: hsqldb ..................................... SUCCESS [  0.866 s]
[INFO] sqlg-h2-parent ..................................... SUCCESS [  0.005 s]
[INFO] sqlg :: h2 dialect ................................. SUCCESS [  1.018 s]
[INFO] sqlg :: h2 ......................................... SUCCESS [  0.750 s]
[INFO] sqlg :: sqlg ....................................... SUCCESS [  0.005 s]
[INFO] sqlg :: cockroachdb dialect ........................ SUCCESS [  1.049 s]
[INFO] sqlg :: cockroachdb ................................ SUCCESS [  0.058 s]
[INFO] sqlg :: sqlg-mariadb-parent ........................ SUCCESS [  0.010 s]
[INFO] sqlg :: mariadb dialect ............................ SUCCESS [  0.991 s]
[INFO] sqlg :: mariadb .................................... SUCCESS [  0.079 s]
[INFO] sqlg :: sqlg-mysql-parent .......................... SUCCESS [  0.007 s]
[INFO] sqlg :: mysql dialect .............................. SUCCESS [  1.098 s]
[INFO] sqlg :: mysql ...................................... SUCCESS [  0.073 s]
[INFO] sqlg-mssqlserver-parent ............................ SUCCESS [  0.006 s]
[INFO] sqlg :: mssqlserver dialect ........................ SUCCESS [  1.166 s]
[INFO] sqlg :: mssqlserver ................................ SUCCESS [  0.731 s]
[INFO] sqlg :: benchmark .................................. SUCCESS [  1.598 s]
[INFO] sqlg :: benchmark-postgres ......................... SUCCESS [  2.568 s]
[INFO] sqlg :: benchmark-hsqldb ........................... SUCCESS [  2.239 s]
[INFO] sqlg :: benchmark-h2 ............................... SUCCESS [  2.211 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.642 s
[INFO] Finished at: 2018-06-26T08:52:14+02:00
[INFO] Final Memory: 267M/1586M
[INFO] ------------------------------------------------------------------------
pieter@pieter-Precision-7510:~/Downloads/sqlg/sqlg$ 
pieter@pieter-Precision-7510:~/Downloads/sqlg/sqlg$ cd ../../tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin/
pieter@pieter-Precision-7510:~/Downloads/tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin$ ./gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: tinkerpop.tinkergraph
gremlin> :install org.umlg sqlg-postgres 1.5.2-SNAPSHOT
==>Loaded: [org.umlg, sqlg-postgres, 1.5.2-SNAPSHOT]
gremlin> :plugin list
==>tinkerpop.server[active]
==>tinkerpop.gephi
==>tinkerpop.utilities[active]
==>tinkerpop.sugar
==>tinkerpop.credentials
==>tinkerpop.tinkergraph[active]
==>sqlg.postgres
gremlin> :plugin use sqlg.postgres
==>sqlg.postgres activated
gremlin> graph = SqlgGraph.open('/home/pieter/Projects/sqlg/sqlg/sqlg-postgres-parent/sqlg-postgres-dialect/src/test/resources//sqlg.properties')
java.lang.IllegalStateException
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.lang.IllegalStateException
	at org.apache.tinkerpop.gremlin.structure.Graph.traversal(Graph.java:159)
	at org.umlg.sqlg.structure.SqlgGraph.traversal(SqlgGraph.java:348)
	at org.umlg.sqlg.structure.SqlgGraph.topology(SqlgGraph.java:352)
	at org.umlg.sqlg.structure.topology.TopologyManager.updateGraph(TopologyManager.java:50)
	at org.umlg.sqlg.structure.SqlgStartupManager.createOrUpdateGraph(SqlgStartupManager.java:178)
	at org.umlg.sqlg.structure.SqlgStartupManager.loadSqlgSchema(SqlgStartupManager.java:97)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:247)
	at org.umlg.sqlg.structure.SqlgGraph.open(SqlgGraph.java:258)
	at org.umlg.sqlg.structure.SqlgGraph$open.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at groovysh_evaluate.run(groovysh_evaluate:3)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:71)
	at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:196)
	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.super$3$execute(GremlinGroovysh.groovy)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:72)
	at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:122)
	at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:95)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:130)
	at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:59)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:89)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:146)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:453)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.tinkerpop.gremlin.structure.Graph.traversal(Graph.java:157)
	... 53 more
Caused by: java.lang.IllegalStateException: org.umlg.sqlg.structure.SqlgGraph
	at org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies$GlobalCache.getStrategies(TraversalStrategies.java:270)
	at org.umlg.sqlg.structure.SqlgGraphTraversalSource.<init>(SqlgGraphTraversalSource.java:15)
	... 58 more
Caused by: java.lang.ClassNotFoundException: org.umlg.sqlg.structure.SqlgGraph
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.tinkerpop.gremlin.process.traversal.TraversalStrategies$GlobalCache.getStrategies(TraversalStrategies.java:260)
	... 59 more
gremlin>exit:
pieter@pieter-Precision-7510:~/Downloads/tinkerpop/apache-tinkerpop-gremlin-console-3.3.3/bin$ ./gremlin.sh 

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
plugin activated: sqlg.postgres
plugin activated: tinkerpop.tinkergraph
gremlin> :plugin use sqlg.postgres
==>sqlg.postgres activated
gremlin> graph = SqlgGraph.open('/home/pieter/Projects/sqlg/sqlg/sqlg-postgres-parent/sqlg-postgres-dialect/src/test/resources/sqlg.properties')
==>sqlggraph[SqlGraph] (jdbc:postgresql://localhost:5432/sqlgraphdb)
gremlin> g = graph.traversal()
==>sqlggraphtraversalsource[sqlggraph[SqlGraph] (jdbc:postgresql://localhost:5432/sqlgraphdb), standard]
gremlin> g.V().count()
==>0
gremlin>
```

Afraid its quite a story.
Looks like groovy grapes does not know about the maven snapshot repositories so I had to manually install `Sqlg` `1.5.2-SNAPSHOT`
I plan to release `1.5.2` by Friday, after that the manual install step should not be necessary.

Also remember to `:exit` the console first after running `:install org.umlg sqlg-postgres 1.5.2-SNAPSHOT` for the first time. This ensures that the console loads the `Sqlg` jars into its classpath.

**Comment by rmanzar** [comment]
After manually installing sqlg using mvn clean install -DskipTests ( i do get BUILD SUCCESS ), but the install still gives the same error , i believe it is something to do with gremlin proxy.

I have this for ./groovy/grapeConfig.xml

<ivysettings>
  <settings defaultResolver="downloadGrapes"/>
  <resolvers>
    <chain name="downloadGrapes">
      <filesystem name="cachedGrapes">
        <ivy pattern="${user.home}/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml"/>
        <artifact pattern="${user.home}/.groovy/grapes/[organisation]/[module]/[type]s/[artifact]-[revision].[ext]"/>
      </filesystem>
      <ibiblio name="local" root="file:${user.home}/.m2/repository/" m2compatible="true"/>
      <ibiblio name="codehaus" root="http://repository.codehaus.org/" m2compatible="true"/>
      <ibiblio name="central" root="http://central.maven.org/maven2/" m2compatible="true"/>
      <ibiblio name="jitpack" root="https://jitpack.io" m2compatible="true"/>
      <ibiblio name="java.net2" root="http://download.java.net/maven/2/" m2compatible="true"/>
     </chain>
  </resolvers>
</ivysettings>

Please let me know if something is wrong with that proxy. ( used it from https://github.com/blazegraph/tinkerpop3/issues/4)

**Comment by pietermartin** [comment]
Ah, can you post your `grapeConfig.xml`?
I do not have one at all on my machine at `.groovy`

**Comment by rmanzar** [comment]
Actually, i had put that but i noticed that when i included link, it took away the html content.
 I tried frist without this as you mentioned rm -Rf ~.groovy, then tried the grapeConfig.xml with the content belwo

<ivysettings>
  <settings defaultResolver="downloadGrapes"/>
  <resolvers>
    <chain name="downloadGrapes">
      <filesystem name="cachedGrapes">
        <ivy pattern="${user.home}/.groovy/grapes/[organisation]/[module]/ivy-[revision].xml"/>
        <artifact pattern="${user.home}/.groovy/grapes/[organisation]/[module]/[type]s/[artifact]-[revision].[ext]"/>
      </filesystem>
      <ibiblio name="local" root="file:${user.home}/.m2/repository/" m2compatible="true"/>
      <ibiblio name="codehaus" root="http://repository.codehaus.org/" m2compatible="true"/>
      <ibiblio name="central" root="http://central.maven.org/maven2/" m2compatible="true"/>
      <ibiblio name="jitpack" root="https://jitpack.io" m2compatible="true"/>
      <ibiblio name="java.net2" root="http://download.java.net/maven/2/" m2compatible="true"/>
     </chain>
  </resolvers>
</ivysettings>

**Comment by rmanzar** [comment]
Looks like it again took away the content, please see below the post by kuzeko commented on Feb 23, 2017  on [https://github.com/blazegraph/tinkerpop3/issues/4]

**Comment by rmanzar** [comment]
I am now able to install plugin with -e option 
echo ":install org.umlg sqlg-postgres 1.5.2-SNAPSHOT" > init.groovy
bin/gremlin.sh -e init.groovy

but now get bunch of error after the (almost 4000 lines), I am pasting first few lines and last few lines of error here.

gremlin> :plugin use sqlg.postgres
==>sqlg.postgres activated
gremlin>  graph = SqlgGraph.open('/apps/opt/landingpad/sqlg/sqlg-postgres-parent/sqlg-postgres-dialect/src/test/resources/sqlg.properties')
Jun 27, 2018 10:27:03 AM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: SQLException occurred while connecting to localhost:5432
org.postgresql.util.PSQLException: FATAL: database "sqlgraphdb" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

Jun 27, 2018 10:27:03 AM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: SQLException occurred while connecting to localhost:5432
org.postgresql.util.PSQLException: FATAL: database "sqlgraphdb" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

Jun 27, 2018 10:27:03 AM org.postgresql.Driver connect
SEVERE: Connection error:



WARN  com.mchange.v2.resourcepool.BasicResourcePool  - com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask@52317d27 -- Acquisition Attempt Failed!!! Clearing pending acquires. While trying to acquire a needed new resource, we failed to succeed more than the maximum number of allowed acquisition attempts (30). Last acquisition attempt exception:
org.postgresql.util.PSQLException: FATAL: database "sqlgraphdb" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2566)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:131)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:210)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:452)
        at org.postgresql.Driver.connect(Driver.java:254)
        at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
WARN  com.mchange.v2.resourcepool.BasicResourcePool  - Having failed to acquire a resource, com.mchange.v2.resourcepool.BasicResourcePool@7ec58feb is interrupting all Threads waiting on a resource to check out. Will try again in response to new client requests.
java.sql.SQLException: Connections could not be acquired from the underlying database!
Type ':help' or ':h' for help.
Display stack trace? [yN]

**Comment by pietermartin** [comment]
The sqlg.properties you passed in to your graph contains,
```
jdbc.url=jdbc:postgresql://localhost:5432/sqlgraphdb
jdbc.username=postgres
jdbc.password=postgres
```

Sqlg does not create the database nor the user. You have to create that and pass in the appropriate properties to the database you created.

**Comment by rmanzar** [comment]
when tried to connect to postgres (default) db, connects fine.

Finally,  I appreciate all your help big time.

==>sqlg.postgres activated
gremlin> graph = SqlgGraph.open('/apps/opt/landingpad/sqlg/sqlg-postgres-parent/sqlg-postgres-dialect/src/test/resources/sqlg.properties')
==>sqlggraph[SqlGraph] (jdbc:postgresql://localhost:5432/postgres)
gremlin> g = graph.traversal()
==>sqlggraphtraversalsource[sqlggraph[SqlGraph] (jdbc:postgresql://localhost:5432/postgres), standard]
gremlin> g.V().count()
==>0
gremlin>

**Comment by pietermartin** [comment]
nice!

**Comment by rmanzar** [comment]
just curious, if you have some sample data for postgres (both the schemas and data)  that works and we can query through gremlin.

**Comment by rmanzar** [comment]
When do you plan to post 1.5.2 in the repository, we are unable to move forward.

**Comment by pietermartin** [comment]
I am hoping to do it this weekend. There is one test failure on MsSqlServer. Once that is sorted then I can release.

**Comment by pietermartin** [comment]
Some feedback. I am traveling at the moment and do not have the computer with MsSqlServer running on it with me. Unfortunately i am unable to install it now as I am running Ubuntu 18.04 and MsSqlServer only works on Ubuntu 16.
I get back home on Tuesday so will try fix it then.

**Comment by pietermartin** [comment]
Closing this one, open it again if you have issues.
