### ISSUE TITLE
NullPointerException when using cache.vertices

### ISSUE THREAD

**Issue by allenhadden** [pietermartin/sqlg#414]
Specifically, it can happen in the following situation:

- cache.vertices is true
- identifiers are being used for vertices
- a given edge label can be between multiple vertex labels
- bothE().otherV() is used in a subsequent traversal

This test case reproduces the problem.  I _think_ I've gotten it down to a minimum, but it wouldn't surprise me to find that there are irrelevant bits in the test:

```
    @Test
    public void testVertexCacheWithIdentifiers() {
        // This is testing a very specific case that previously failed:
        //
        // - cache.vertices is true
        // - identifiers are being used for vertices
        // - a given edge label can be between multiple vertex labels
        // - bothE().otherV() is used in a subsequent traversal

        Topology topology = this.sqlgGraph.getTopology();

        Map<String, PropertyType> vertexProperties = new HashMap<>();
        vertexProperties.put("id", PropertyType.STRING);
        vertexProperties.put("name", PropertyType.STRING);

        ListOrderedSet<String> identifiers = ListOrderedSet.listOrderedSet(Collections.singletonList("id"));

        VertexLabel vertexLabelA = topology.ensureVertexLabelExist("A", vertexProperties, identifiers);
        VertexLabel vertexLabelB = topology.ensureVertexLabelExist("B", vertexProperties, identifiers);
        VertexLabel vertexLabelC = topology.ensureVertexLabelExist("C", vertexProperties, identifiers);

        Map<String, PropertyType> edgeProperties = new HashMap<>();
        edgeProperties.put("id", PropertyType.STRING);
        edgeProperties.put("how", PropertyType.STRING);

        topology.ensureEdgeLabelExist("related", vertexLabelA, vertexLabelB, edgeProperties);
        topology.ensureEdgeLabelExist("related", vertexLabelA, vertexLabelC, edgeProperties);

        Vertex v1 = this.sqlgGraph.addVertex(T.label, "A", "id", "1", "name", "joe");
        Vertex v2 = this.sqlgGraph.addVertex(T.label, "B", "id", "2", "name", "frank");

        v1.addEdge("related", v2, "how", "friend");

        // Without the fix, this will trigger a NPE in RecordId.ID.hashCode() because "identifiers" contains a null.
        Vertex v2a = sqlgGraph.traversal().V().has("id", "1").bothE().otherV().next();

        Assert.assertEquals(v2, v2a);
    }
```

This is the stack trace when it occurs:

```
java.lang.NullPointerException
	at org.umlg.sqlg.structure.RecordId$ID.hashCode(RecordId.java:496)
	at org.umlg.sqlg.structure.RecordId.hashCode(RecordId.java:216)
	at java.base/java.util.WeakHashMap.hash(WeakHashMap.java:298)
	at java.base/java.util.WeakHashMap.get(WeakHashMap.java:397)
	at org.umlg.sqlg.structure.TransactionCache.putVertexIfAbsent(TransactionCache.java:127)
	at org.umlg.sqlg.structure.SqlgTransaction.putVertexIfAbsent(SqlgTransaction.java:301)
	at org.umlg.sqlg.structure.SqlgVertex.of(SqlgVertex.java:68)
	at org.umlg.sqlg.structure.SqlgEdge.loadInVertex(SqlgEdge.java:444)
	at org.umlg.sqlg.sql.parse.SchemaTableTree.loadEdgeInOutVertices(SchemaTableTree.java:2759)
	at org.umlg.sqlg.util.SqlgUtil.loadLabeledElements(SqlgUtil.java:200)
	at org.umlg.sqlg.util.SqlgUtil.loadResultSetIntoResultIterator(SqlgUtil.java:108)
	at org.umlg.sqlg.util.SqlgUtil.loadResultSetIntoResultIterator(SqlgUtil.java:69)
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.iterateRegularQueries(SqlgCompiledResultIterator.java:265)
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.hasNextLazy(SqlgCompiledResultIterator.java:106)
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.hasNext(SqlgCompiledResultIterator.java:78)
	at org.umlg.sqlg.step.SqlgGraphStep.processNextStart(SqlgGraphStep.java:80)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:129)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:39)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:204)
	at org.umlg.sqlg.test.vertex.TestVertexCache.testVertexCacheWithIdentifiers(TestVertexCache.java:74)
```

And here is a candidate fix.  The biggest question I have is if there's something upstream that should change instead.  I mean, should "identifiers" ever contain null values?  Another question is...if this is the right place to fix the problem, is "equals" being handled properly?  That is, if you have two ID objects that both contain [null], should they be equal or not?  I said "no" because that felt like the safest approach given my limited knowledge of the situation.  I suspect it'll just mean that some things that could have been cached will not be.

```
diff --git a/sqlg-core/src/main/java/org/umlg/sqlg/structure/RecordId.java b/sqlg-core/src/main/java/org/umlg/sqlg/structure/RecordId.java
index 45c5a9fc..8c5e5963 100644
--- a/sqlg-core/src/main/java/org/umlg/sqlg/structure/RecordId.java
+++ b/sqlg-core/src/main/java/org/umlg/sqlg/structure/RecordId.java
@@ -482,6 +482,11 @@ public class RecordId implements KryoSerializable, Comparable {
             if (this.sequenceId != null) {
                 return this.sequenceId.equals(otherID.sequenceId);
             } else {
+                // identifiers can sometimes contain null, but in that case they should
+                // never be equal to anything else.
+                if (this.identifiers.contains(null) || otherID.identifiers.contains(null)) {
+                    return false;
+                }
                 return this.identifiers.equals(otherID.identifiers);
             }
         }
@@ -493,7 +498,11 @@ public class RecordId implements KryoSerializable, Comparable {
             } else {
                 StringBuilder sb = new StringBuilder();
                 for (Object identifier : this.identifiers) {
-                    sb.append(identifier.toString());
+                    // identifiers can be null in various cases.  don't include them in the hash.  note they
+                    // will never be considered equal.
+                    if (identifier != null) {
+                        sb.append(identifier.toString());
+                    }
                 }
                 return sb.toString().hashCode();
             }
```

**Comment by pietermartin** [comment]
Thanks for the test case, I am having a look.

**Comment by pietermartin** [comment]
Your fix was in the right direction but that code should not even execute, as the in/out vertex of the edge does not exist.
For non identifier vertices there was already a check that I missed with identifiers.

**Comment by allenhadden** [comment]
Thanks for the quick response on this!
