### ISSUE TITLE
Conflicting getter definitions for property "id": org.umlg.sqlg.structure.RecordId#getId(0 params)

### ISSUE THREAD

**Issue by veqryn** [pietermartin/sqlg#429]
I have the grateful dead json loaded into a graph.

I am running `g.V()` on this visualizer tool: https://github.com/prabushitha/gremlin-visualizer

The result are the following logs from the gremlin-server:
```java
could not be serialized by org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0.
org.apache.tinkerpop.shaded.jackson.databind.JsonMappingException: Conflicting getter definitions for property "id": org.umlg.sqlg.structure.RecordId#getId(0 params) vs org.umlg.sqlg.structure.RecordId#getID(0 params)
        at org.apache.tinkerpop.shaded.jackson.databind.JsonMappingException.from(JsonMappingException.java:295)
        at org.apache.tinkerpop.shaded.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1309)
        at org.apache.tinkerpop.shaded.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1427)
        at org.apache.tinkerpop.shaded.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:521)
        at org.apache.tinkerpop.shaded.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:799)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
        at org.apache.tinkerpop.shaded.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3058)
        at org.apache.tinkerpop.shaded.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
        at org.apache.tinkerpop.gremlin.structure.io.graphson.JavaUtilSerializersV3d0$MapJacksonSerializer.serialize(JavaUtilSerializersV3d0.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.graphson.JavaUtilSerializersV3d0$MapJacksonSerializer.serializeWithType(JavaUtilSerializersV3d0.java:67)
        at org.apache.tinkerpop.gremlin.structure.io.graphson.JavaUtilSerializersV3d0$MapJacksonSerializer.serializeWithType(JavaUtilSerializersV3d0.java:49)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at org.apache.tinkerpop.shaded.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3058)
        at org.apache.tinkerpop.shaded.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
        at org.apache.tinkerpop.gremlin.structure.io.graphson.JavaUtilSerializersV3d0$ListJacksonSerializer.serialize(JavaUtilSerializersV3d0.java:127)
        at org.apache.tinkerpop.gremlin.structure.io.graphson.JavaUtilSerializersV3d0$ListJacksonSerializer.serializeWithType(JavaUtilSerializersV3d0.java:135)
        at org.apache.tinkerpop.gremlin.structure.io.graphson.JavaUtilSerializersV3d0$ListJacksonSerializer.serializeWithType(JavaUtilSerializersV3d0.java:118)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
        at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0$ResponseMessageSerializer.ser(AbstractGraphSONMessageSerializerV2d0.java:281)
        at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0$ResponseMessageSerializer.serializeWithType(AbstractGraphSONMessageSerializerV2d0.java:255)
        at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0$ResponseMessageSerializer.serializeWithType(AbstractGraphSONMessageSerializerV2d0.java:240)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at org.apache.tinkerpop.shaded.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4409)
        at org.apache.tinkerpop.shaded.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3687)
        at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0.serializeResponseAsBinary(AbstractGraphSONMessageSerializerV2d0.java:85)
        at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.makeFrame(AbstractOpProcessor.java:291)
        at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:167)
        at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$5(AbstractEvalOpProcessor.java:263)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:283)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Conflicting getter definitions for property "id": org.umlg.sqlg.structure.RecordId#getId(0 params) vs org.umlg.sqlg.structure.RecordId#getID(0 params)
        at org.apache.tinkerpop.shaded.jackson.databind.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuilder.java:440)
        at org.apache.tinkerpop.shaded.jackson.databind.introspect.BeanPropertyDefinition.getAccessor(BeanPropertyDefinition.java:188)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:698)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:573)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:384)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:286)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:231)
        at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165)
        at org.apache.tinkerpop.shaded.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1474)
        at org.apache.tinkerpop.shaded.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1422)
        ... 36 more
```

**Comment by veqryn** [comment]
I also tried another visualization tool: https://github.com/dboreham/graphexp/tree/fix-gremlin-3-5-issue

Got a similar error, but for v3d0:
`could not be serialized by org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0.
org.apache.tinkerpop.shaded.jackson.databind.JsonMappingException: Conflicting getter definitions for property "id": org.umlg.sqlg.structure.RecordId#getId(0 params) vs org.umlg.sqlg.structure.RecordId#getID(0 params)`

**Comment by pietermartin** [comment]
`RecordId.getId()` lower case has been deprecated. Can you perhaps see if it will work with that method removed?

**Comment by veqryn** [comment]
How do I compile the project into whatever it needs to be?

**Comment by pietermartin** [comment]
I'll remove that method on the current `master` branch and deploy it to Sonatype's snapshot repositories. Then you will be able to access it via `<version>2.1.6-SNAPSHOT</version>`. Just need some time to make sure all tests are passing.

**Comment by veqryn** [comment]
Sounds good, let me know when the snapshot is ready to download. Alternatively, it probably wouldn't be too hard to point either of those two visualization tools at gremlin server, once you get that running.

**Comment by pietermartin** [comment]
Sqlg `2.1.6-SNAPSHOT` is deployed.

**Comment by veqryn** [comment]
Hm..., I get an error trying to download it:
```
+ /opt/gremlin-server/bin/gremlin-server.sh install org.umlg sqlg-postgres 2.1.6-SNAPSHOT
Installing dependency org.umlg sqlg-postgres 2.1.6-SNAPSHOT
java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: org.umlg#sqlg-postgres;2.1.6-SNAPSHOT: not found]
Could not install the dependency: Error grabbing Grapes -- [unresolved dependency: org.umlg#sqlg-postgres;2.1.6-SNAPSHOT: not found]
```

**Comment by pietermartin** [comment]
Ok, I am not all that familiar with grapes but it is deployed,
https://oss.sonatype.org/content/repositories/snapshots/org/umlg/sqlg-postgres-dialect/2.1.6-SNAPSHOT/sqlg-postgres-dialect-2.1.6-20211122.052720-1.pom

I recall that the console and grapes is a bit dum and caches stuff. Maybe try a clean directory or to clear the cache?

**Comment by veqryn** [comment]
I tried both gremlin-server and also gremlin-console, and both have the same issue. I am running in a docker container, so there isn't any grapes cache to worry about. Here is console:
```
gremlin> :install org.umlg sqlg-postgres 2.1.6-SNAPSHOT
==>Error grabbing Grapes -- [unresolved dependency: org.umlg#sqlg-postgres;2.1.6-SNAPSHOT: not found]
gremlin> :install org.umlg sqlg-postgres 2.1.5
==>Loaded: [org.umlg, sqlg-postgres, 2.1.5] - restart the console to use [sqlg.postgres]
gremlin>
```

The jars that grapes downloads for 2.1.5 are the following:
```
$ ls jars/sqlg-postgres/lib
c3p0-0.9.5.5.jar                error_prone_annotations-2.7.1.jar  groovy-json-2.5.14-indy.jar         jackson-core-2.10.0.pr1.jar      listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
caffeine-2.3.1.jar              exp4j-0.4.8.jar                    groovy-jsr223-2.5.14-indy.jar       jackson-databind-2.10.0.pr1.jar  mchange-commons-java-0.2.19.jar
checker-qual-3.12.0.jar         failureaccess-1.0.1.jar            groovy-swing-2.5.14.jar             javapoet-1.8.0.jar               picocli-4.3.2.jar
commons-beanutils-1.9.4.jar     gremlin-core-3.5.1.jar             groovy-templates-2.5.14.jar         javatuples-1.2.jar               postgis-jdbc-2.1.7.2.jar
commons-collections-3.2.2.jar   gremlin-groovy-3.5.1.jar           groovy-xml-2.5.14.jar               jbcrypt-0.4.jar                  postgresql-42.2.2.jar
commons-collections4-4.4.jar    gremlin-shaded-3.5.1.jar           guava-31.0.1-jre.jar                jcabi-log-0.14.jar               slf4j-api-1.7.25.jar
commons-configuration2-2.7.jar  groovy-2.5.14-indy.jar             hppc-0.7.1.jar                      jcabi-manifests-1.1.jar          snakeyaml-1.27.jar
commons-lang3-3.11.jar          groovy-cli-picocli-2.5.14.jar      ivy-2.4.0.jar                       jcl-over-slf4j-1.7.25.jar        sqlg-core-2.1.5.jar
commons-logging-1.2.jar         groovy-console-2.5.14.jar          j2objc-annotations-1.3.jar          jline-2.14.6.jar                 sqlg-postgres-2.1.5.jar
commons-text-1.9.jar            groovy-groovysh-2.5.14-indy.jar    jackson-annotations-2.10.0.pr1.jar  jsr305-3.0.2.jar                 sqlg-postgres-dialect-2.1.5.jar

$ ls jars/sqlg-postgres/plugin
c3p0-0.9.5.5.jar                   failureaccess-1.0.1.jar     jackson-annotations-2.10.0.pr1.jar  listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar  sqlg-core-2.1.5.jar
checker-qual-3.12.0.jar            gremlin-groovy-3.5.1.jar    jackson-core-2.10.0.pr1.jar         mchange-commons-java-0.2.19.jar                                 sqlg-postgres-2.1.5.jar
commons-collections4-4.4.jar       guava-31.0.1-jre.jar        jackson-databind-2.10.0.pr1.jar     postgis-jdbc-2.1.7.2.jar                                        sqlg-postgres-dialect-2.1.5.jar
error_prone_annotations-2.7.1.jar  j2objc-annotations-1.3.jar  jsr305-3.0.2.jar                    postgresql-42.2.2.jar
```

So I went and manually downloaded the 2.1.6-SNAPSHOT jars for sqlg*, and then mounted them into docker.

With this, everything was able to run, and the two different visualizers were able to make queries successfully.

The only problem is that, the visualizers are maybe expecting more data or something.

Running `g.V()` on https://github.com/prabushitha/gremlin-visualizer just gives a generic error message: `Invalid query. Please execute a query to get a set of vertices`
This is despite inspecting and showing on the network tab in chrome that all queries returned successfully with data showing the vertices.

And graphexp is able to show the nodes, but won't show any edges or labels.

Maybe not a sqlg problem, I don't really know. I do know these tools work with other graph databases (i did a quick test with JanusGraph), and they show a network of nodes and the edges connecting them.

**Comment by pietermartin** [comment]
Ok, afraid I don't know either without trying it out. Maybe compare a small result set from `JanusGraph` with that of `Sqlg`?

**Comment by pietermartin** [comment]
Closing this as I am not investigating it. Feel free to reopen.
