### ISSUE TITLE
sql compiled traversal cache 

### ISSUE THREAD

**Issue by pietermartin** [pietermartin/sqlg#487]
Getting the below exception, investigate
```
org.umlg.sqlg.sql.parse.AliasMapHolder@71960ecb) size=1000 maxSize=1000 This should not occur if your keys are immutable, and you have used synchronization properly.
	at org.apache.commons.collections4.map.LRUMap.reuseMapping(LRUMap.java:384) ~[commons-collections4-4.4.jar:4.4]
	at org.apache.commons.collections4.map.LRUMap.addMapping(LRUMap.java:349) ~[commons-collections4-4.4.jar:4.4]
	at org.apache.commons.collections4.map.AbstractHashedMap.put(AbstractHashedMap.java:289) ~[commons-collections4-4.4.jar:4.4]
	at org.umlg.sqlg.structure.SchemaTableTreeCache.put(SchemaTableTreeCache.java:24) ~[sqlg-core-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
	at org.umlg.sqlg.structure.SchemaTableTreeCache.sql(SchemaTableTreeCache.java:51) ~[sqlg-core-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
	at org.umlg.sqlg.strategy.SqlgSqlExecutor.executeRegularQuery(SqlgSqlExecutor.java:76) ~[sqlg-core-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.executeRegularQuery(SqlgCompiledResultIterator.java:248) ~[sqlg-core-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.hasNextLazy(SqlgCompiledResultIterator.java:121) ~[sqlg-core-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
	at org.umlg.sqlg.structure.SqlgCompiledResultIterator.hasNext(SqlgCompiledResultIterator.java:78) ~[sqlg-core-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
	at org.umlg.sqlg.step.SqlgGraphStep.processNextStart(SqlgGraphStep.java:78) ~[sqlg-core-3.0.1-SNAPSHOT.jar:3.0.1-SNAPSHOT]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:135) ~[gremlin-core-3.6.4.jar:3.6.4]
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:40) ~[gremlin-core-3.6.4.jar:3.6.4]
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:184) ~[gremlin-core-3.6.4.jar:3.6.4]
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:122) ~[gremlin-core-3.6.4.jar:3.6.4]
	at com.digitata.utils.VendorTechnologyUtils.getNetworkSoftwareVersionFor(VendorTechnologyUtils.java:39) ~[cm-entity-6.0.0.jar:?]
	at com.rorotika.cm.etl.listeners.EtlListener.lambda$start$4(EtlListener.java:165) ~[etl-etling-6.0.0.jar:?]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:73) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.publisher.MonoRunnable.call(MonoRunnable.java:32) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:227) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.10.jar:3.4.10]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
```

**Comment by pietermartin** [comment]
The cache has been removed for now, it needs way more attention to be a worthwhile feature
