### ISSUE TITLE
Exception in Optional step with hasLabel

### ISSUE THREAD

**Issue by yura-ata** [pietermartin/sqlg#98]
ArrayIndexOutOfBoundsException is thrown when Optional step contains hasLabel.

Example:
`this.sqlgGraph.traversal().V().optional(out().hasLabel("B")).toList()`
Stack Trace:
java.lang.ArrayIndexOutOfBoundsException: -2

	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.removeStep(DefaultTraversal.java:290)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal$Admin.removeStep(Traversal.java:326)
	at org.umlg.sqlg.strategy.BaseSqlgStrategy.collectHasSteps(BaseSqlgStrategy.java:331)
	at org.umlg.sqlg.strategy.BaseSqlgStrategy.combineSteps(BaseSqlgStrategy.java:189)
	at org.umlg.sqlg.strategy.SqlgGraphStepStrategy.apply(SqlgGraphStepStrategy.java:64)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies.applyStrategies(DefaultTraversalStrategies.java:86)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:113)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:150)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:111)
	at org.umlg.sqlg.test.gremlincompile.TestGremlinOptional.testOptionalWithHasLabel(TestGremlinOptional.java:40)

**Comment by yura-ata** [comment]
Small question:
would it be enough in method 'BaseSqlgStrategy.collectHasSteps' to check if traversal steps contains current step before removal, or modifications in 'flattenChooseStep' would be required

**Comment by pietermartin** [comment]
Yeah, pretty much, however why did I think it is there in the first place?
The reason is that the owning OptionalStep has been removed. The same is true for RepeatStep however it does not optimize if there is a HasStep so RepeatSteps do not have this problem. The problem regarding RepeatSteps is however that it should be able to optimize even if there is a HasStep.

I'll push a fix soon, just running all the tests.

**Comment by yura-ata** [comment]
thanks
